USE [master]
GO

/****** Object:  Database [TP-Secu]    Script Date: 20/11/2017 11:43:18 ******/
CREATE DATABASE [TP-Secu]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TP-Secu', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TP-Secu.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TP-Secu_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\TP-Secu_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TP-Secu] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TP-Secu].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TP-Secu] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TP-Secu] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TP-Secu] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TP-Secu] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TP-Secu] SET ARITHABORT OFF 
GO

ALTER DATABASE [TP-Secu] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TP-Secu] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TP-Secu] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TP-Secu] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TP-Secu] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TP-Secu] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TP-Secu] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TP-Secu] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TP-Secu] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TP-Secu] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TP-Secu] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TP-Secu] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TP-Secu] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TP-Secu] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TP-Secu] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TP-Secu] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TP-Secu] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TP-Secu] SET RECOVERY FULL 
GO

ALTER DATABASE [TP-Secu] SET  MULTI_USER 
GO

ALTER DATABASE [TP-Secu] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TP-Secu] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TP-Secu] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TP-Secu] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TP-Secu] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TP-Secu] SET QUERY_STORE = OFF
GO

USE [TP-Secu]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TP-Secu] SET  READ_WRITE 
GO

